export const identifiers = {
    APP: 'APP',
    FIREBASE: 'FIREBASE',
    DATABASE: 'DATABASE',
    AUTH: 'AUTH',
    PRODUCTS_REPOSITORY: 'PRODUCTS_REPOSITORY',
    DISCOUNT_REPOSITORY: 'DISCOUNT_REPOSITORY',
    AUTH_SERVICE: 'AUTH_SERVICE'
}